### PR TITLE
Support sonata-project/media-bundle ^3.0

### PR DESCRIPTION
**Pull request by ruscon**

### CODE REVIEW

**Comment by dunglas** [comment]
@ruscon Are the tests green locally?

**Comment by ruscon** [comment]
```
➜  CoopTilleulsCKEditorSonataMediaBundle git:(master) phpunit
PHPUnit 4.3.4 by Sebastian Bergmann.

Configuration read from /Users/ruscon/projects/CoopTilleulsCKEditorSonataMediaBundle/phpunit.xml.dist

.

Time: 113 ms, Memory: 3.50Mb

OK (1 test, 7 assertions)
```

**Comment by ruscon** [comment]
tag it plz after

**Comment by dunglas** [comment]
We need to fix Travis first.

**Comment by ruscon** [comment]
moved https://github.com/coopTilleuls/CoopTilleulsCKEditorSonataMediaBundle/pull/22

**Pull request closed without merging**
